### 1. Регистрация нового пользователя
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "username": "testuser23311111",
  "email": "partyd80111111@gmail.com",
  "password": "password123!"
}

###

### 2. Верификация аккаунта (введи код из консоли/почты)
POST http://localhost:8080/auth/verify
Content-Type: application/json

{
  "email": "partyd80111111@gmail.com",
  "verificationCode": "588716"
}

###

### 3. Авторизация (Получение JWT токена)
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "partyd80111111@gmail.com",
  "password": "password123!"
}

### 

### 4. Создание поста (Пример запроса с токеном)
# Скопируй токен из ответа предыдущего запроса и вставь после слова Bearer
POST http://localhost:8080/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlcjIzMzExMTExIiwiaWF0IjoxNzgwNjY5NTgzLCJleHAiOjE3ODA2NzMxODN9.cVdk_dKTngpglHydSkNbjsnSZ5uICHhqiO6GIKERjig

{
  "content": "Привет, это моя первая публикация в модульном монолите!",
  "mediaUrl": "https://example.com/social-photo.jpg"
}

###

### 5. Подписаться на пользователя (замени {id} на реальный ID)
POST http://localhost:8080/users/2/follow
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlcjIzMzExMTExIiwiaWF0IjoxNzgwNjY5NTgzLCJleHAiOjE3ODA2NzMxODN9.cVdk_dKTngpglHydSkNbjsnSZ5uICHhqiO6GIKERjig

###

### 6. Отписаться от пользователя (замени {id} на реальный ID)
POST http://localhost:8080/users/2/unfollow
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlcjIzMzExMTExIiwiaWF0IjoxNzgwNjY5NTgzLCJleHAiOjE3ODA2NzMxODN9.cVdk_dKTngpglHydSkNbjsnSZ5uICHhqiO6GIKERjig

###

### 7. Получить список подписчиков (замени {id} на реальный ID)
GET http://localhost:8080/users/2/followers?page=0&size=10
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlcjIzMzExMTExIiwiaWF0IjoxNzgwNjY5NTgzLCJleHAiOjE3ODA2NzMxODN9.cVdk_dKTngpglHydSkNbjsnSZ5uICHhqiO6GIKERjig

###

### 8. Получить статистику подписок (замени {id} на реальный ID)
GET http://localhost:8080/users/2/follow-stats
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlcjIzMzExMTExIiwiaWF0IjoxNzgwNjY5NTgzLCJleHAiOjE3ODA2NzMxODN9.cVdk_dKTngpglHydSkNbjsnSZ5uICHhqiO6GIKERjig

###

### 9. Получить ленту новостей
GET http://localhost:8080/posts/feed?page=0&size=10
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlcjIzMzExMTExIiwiaWF0IjoxNzgwNjY5NTgzLCJleHAiOjE3ODA2NzMxODN9.cVdk_dKTngpglHydSkNbjsnSZ5uICHhqiO6GIKERjig