# ===================================================================
# ????????? ???? ?????? PostgreSQL
# ===================================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/demo_db
spring.datasource.username=postgres
spring.datasource.password=5432
spring.datasource.driver-class-name=org.postgresql.Driver

# ?????????????? ?????????? ?????? Hibernate ??? ???????? User ? Post
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===================================================================
# ????????? ????? Gmail (?????????? ??? ???? ??????????)
# ===================================================================
spring.mail.host=smtp.gmail.com

spring.mail.port=587
spring.mail.username=adilgg672@gmail.com
spring.mail.password=qvrzytduihmyqeyk

# ???????????? ????????? ???????????? ??? Google SMTP
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# ===================================================================
# ????????? JWT ??????
# ===================================================================
security.jwt.secret-key=mySuperSecretKeyForJwtTokensThatIsAtLeast32CharactersLong12345

security.jwt.expiration-time=3600000